spring:
  datasource:
#    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/record
    username: root
    password: 
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
#login
api:
  base.path= http://localhost:8080/users